### ISSUE TITLE
Clifford Wolf changed their name and homepage

### ISSUE THREAD

**Issue by Exouxas** [os-fpga/1st-CLaaS#71]
After finding out that the link to the docs page for yosys is faulty in the [FOEDAG repo](https://github.com/os-fpga/FOEDAG) ([FOEDAG issue 318](https://github.com/os-fpga/FOEDAG/issues/318)), I did some research and found that Clifford Wolf has changed both name and homepage.

The reason I'm writing about this is that the [Personal History of this Project](https://github.com/os-fpga/1st-CLaaS/blob/master/doc/Story.md) mentions Clifford Wolf and links to their old website (clifford.at), which is now owned by someone else and promotes gambling sites. I know that the file is old and not modified, but in the interest of keeping it relevant and safe I'd at least like to inform about my findings.

As an alternative to the current link, it could be changed to their github profile https://github.com/clairexen

In case anyone's wondering how the new page(s) were found:
- Used the [wayback machine](https://web.archive.org/) to find the last version of the website before it got changed ([12th of June 2021](https://web.archive.org/web/20210612145407/http://www.clifford.at/))
- Went to [their twitter account](https://twitter.com/oe1cxw)
- Then [their new homepage](https://www.clairexen.net/)
- And lastly to [their github profile](https://github.com/clairexen)

These links are in their github profile.

**Comment by stevehoover** [comment]
Thanks @Exouxas .
